run_lint:
  image: node:latest
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases
  script:
    - npm install
    - npm run lint
